services:
  - type: web
    name: triagemate-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_VERSION
        value: 22.23.1
      - key: ATLAS_URI
        sync: false
      - key: GEMINIAI
        sync: false
